On E0478, use a shorter span pointing only at lifetime instead of whole type
```
error[E0478]: lifetime bound not satisfied
  --> $DIR/E0478.rs:4:37
   |
LL |     child: Box<dyn Wedding<'kiss> + 'SnowWhite>,
   |                                     ^^^^^^^^^^ lifetime bound not satisfied
   |
```
instead of
```
error[E0478]: lifetime bound not satisfied
  --> $DIR/E0478.rs:4:12
   |
LL |     child: Box<dyn Wedding<'kiss> + 'SnowWhite>,
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
```