Detect `impl Default` where fields are literals and `Default::default()` calls
```
error: `impl Default` that could be derived
  --> $DIR/manual-default-impl-could-be-derived.rs:33:1
   |
LL | / impl Default for D {
LL | |     fn default() -> Self {
LL | |         D {
LL | |             x: Default::default(),
...  |
LL | |     }
LL | | }
   | |_^
   |
help: you don't need to manually `impl Default`, you can derive it
   |
LL ~ #[derive(Default)] struct D {
   |
```