sys: reduce visibility of some internal OsStr-related types
I’m honestly not entirely sure why this is needed, but if I try to edit
the file in subsequent commit without this change I’m getting ‘missing
stability attribute’ errors:

    error: struct has missing stability attribute
      --> library/std/src/sys/unix/os_str.rs:22:1
       |
    22 | / pub struct Buf {
    23 | |     pub inner: Vec<u8>,
    24 | | }
       | |_^