Suggest mutable method when iterating over binding
When encountering a for loop that requires a mutable iterator item, we previously suggested changing the method on the iterated expression, but ignored bindings. We now go to the binding's definition and suggest changing the method there too.

```
error[E0594]: cannot assign to `v.v`, which is behind a `&` reference
  --> $DIR/suggest-mut-method-for-loop-hashmap.rs:31:9
   |
LL |     for (_k, v) in x {
   |                    - this iterator yields `&` references
...
LL |         v.v += 1;
   |         ^^^^^^^^ `v` is a `&` reference, so it cannot be written to
   |
help: use mutable method
   |
LL |     let mut x = map.iter_mut();
   |                         ++++
```