core: add core::pattern::Predicate wrapper type
To work around orphan rules, introduce a wrapper type for predicate
functions to be used as pattern.  Specefically, if we want to add
predicat pattern implementation for OsStr type, doing it with a naked
`FnMut` results in compile-time errors:

    error[E0210]: type parameter `F` must be covered by another type when it
                  appears before the first local type (`OsStr`)
    impl<'hs, F: FnMut(char) -> bool> core::pattern::Pattern<&'hs OsStr> for F {
              ^ type parameter `F` must be covered by another type
                when it appears before the first local type (`OsStr`)

std: add predicate pattern support to OsStr

Due to technical limitations adding support for predicate as patterns
on OsStr slices must be done via core::pattern::Predicate wrapper type.
This isn’t ideal but for the time being it’s the best option I've came
up with.

The core of the issue (as I understand it) is that FnMut is a foreign
type in std crate where OsStr is defined.

Using predicate as a pattern on OsStr is the final piece which now
allows parsing command line arguments.