adding LLVM library link path to `run-make`
When moving `coverage` tests from `run-make-fulldeps` to `run-make`,
some targets failed in CI with an obscure message:

failed to execute command: "musl-g++" "-ffunction-sections"
"-fdata-sections" "-fPIC" "-m32" "-march=i686" "-Wl,-melf_i386"
"-static" "-Wa,-mrelax-relocations=no" "-print-file-name=libstdc++.a"

error: No such file or directory (os error 2)

The coverage tests include `# needs-profiler-support` and these are the
first `run-make` tests to require it (as far as I can tell).

There is a special case in `bootstrap` for adding the LLVM library link
path, and it applies to `run-make-fulldeps`. This commit adds it for
`run-make` as well.