Add stability attribute eager expansion test
    error: expected unsuffixed literal or identifier, found `stable_feature`
      --> tests/ui/stability-attribute/eager-expansion.rs:37:32
       |
    LL |               #[stable(feature = stable_feature!($signedness), since = stable_since!($signedness))]
       |                                  ^^^^^^^^^^^^^^
    ...
    LL | / nonzero_integers! {
    LL | |     unsigned NonZeroU8(u8)
    LL | |     unsigned NonZeroU16(u16)
    LL | |     unsigned NonZeroU32(u32)
    ...  |
    LL | |     signed NonZeroI64(u64)
    LL | | }
       | |_- in this macro invocation
       |
       = note: this error originates in the macro `nonzero_integers` (in Nightly builds, run with -Z macro-backtrace for more info)