I noted tonight that using the examples straight away, e.g. in your `main` method or in any other method returning a non-`std::io::Result` value fails, because of reasons mentioned in https://github.com/rust-lang/rfcs/pull/1937.
I suggest uncommenting these parts of the examples, so that the examples are more "copy-pasteable" and show the true requirements for using them. The compilation errors I got wasn't enough to make me realize what the problem was:

```
error[E0277]: the trait bound `std::string::String: std::ops::Try` is not satisfied
```

(Thanks to the helpful people at #rust-beginners who helped me debug it; it was obvious once you knew the prerequisites for using the `?` operator.)