improve panic message on `expect`
This is something that has been bothering me for years,
which (naively) seems simple to fix.

The message passed to `.expect(msg)` is printed in
(at least potentially) confusing way to the user:

```
let x: Option<u32> = None;
x.expect("valid x value");

// thread 'main' panicked at ...:
// valid x value
```

IMO, it would be much better if it got reported as:

```
// thread 'main' panicked at ...:
// expected: valid x value
```

Then, no matter how the message is formulated, it
should be clear that it was the *expectation*, not
the failing condition itself.