On many bindings with move error, limit the number of `Span`s
When a "can't move out of" error would point at too many places, limit the number of spans so that we don't span the terminal.

```
error[E0507]: cannot move out of `f` as enum variant `Foo1` which is behind a shared reference
  --> $DIR/borrowck-move-error-many-places.rs:15:11
   |
LL |     match *f {
   |           ^^
LL |         Foo::Foo1(num1,
   |                   ---- data moved here
LL |                   num2) => (),
   |                   ---- ...and here
LL |         Foo::Foo2(num) => (),
   |                   --- ...and here
LL |         Foo::Foo3(num) => (),
   |                   --- ...and here
LL |         Foo::Foo4(num) => (),
   |                   --- ...and here
   |
   = note: ...and 4 other places
   = note: move occurs because these variables have types that don't implement the `Copy` trait
help: consider removing the dereference here
   |
LL -     match *f {
LL +     match f {
   |
```