IntoInnerError: Provide into_parts
In particular, IntoIneerError only currently provides .error() which
returns a reference, not an owned value.  This is not helpful and
means that a caller of BufWriter::into_inner cannot acquire an owned
io::Error which seems quite wrong.

I have made this insta-stable because I think it ought to be very
uncontroversial.  It doesn't involve promising new facts about the
underlying implementation; it just gives a better access to the facts
which are already implied.  The lack of the usual `into_parts` seems
simply an oversight.

Signed-off-by: Ian Jackson <ijackson@chiark.greenend.org.uk>