Detect when unmet lifetime obligation comes from use of `Self` literal
When using `Self { ... }`, it introduces lifetime requirements from the `impl` that might be more strict than using the actual type's literal. We now point that out.

```
error: lifetime may not live long enough
  --> $DIR/conflicting-lifetime-bounds-from-impl-in-self-literal.rs:21:25
   |
LL |     impl<'a> Path<'a> {
   |          -- lifetime `'a` defined here
...
LL |         pub fn sub(&mut self) -> Path/*<'_>*/ {
   |                    - let's call the lifetime of this reference `'1`
...
LL |             Self {
   |             ---- requires lifetime `'a` from the `impl`
...
LL |                 string: self.string,
   |                         ^^^^^^^^^^^ this usage requires that `'1` must outlive `'a`
   |
help: consider using the type's name directly instead, to avoid conflicting lifetime bounds from the `impl`
   |
LL -             Self {
LL +             Path {
   |
```