Update bootstrap to use -Zembed-metadata=no instead of -Zno-embed-metadata
The recent Cargo submodule update picked up <https://github.com/rust-lang/cargo/pull/17149>

However, bootstrap was still using the old name, resulting in:

```
Building stage1 library artifacts (stage1 -> stage1, arm64ec-pc-windows-msvc)
error: unknown `-Z` flag specified: no-embed-metadata
```

Fix is to switch to the rename.

I also removed the diff in the Cranelift setup script, since they must have already hit this issue and no longer need the workaround.