Tweak suggestion of "unreachable due to never pattern"
Use more accurate span when suggesting to remove guard and body of a never-pattern match arm (`feature(never_patterns)`].

```
error: a guard on a never pattern will never be run
  --> $DIR/ICE-119271-never-arm-attr-in-guard.rs:8:13
   |
LL |             false
   |             ^^^^^
   |
help: remove the guard, leaving only the pattern
   |
LL -         Some(!)
LL -
LL -             if #[deny(unused_mut)]
LL -             false
LL +         Some(!)
   |
```