wip: Better error when violating `for<'a> T: 'a`
This is a work in progress that gives the right result but not with code worth
checking in yet. Please see the comments starting with `Q:` in the diff.

```
error[E0592]: the type `&'b i32` does not fulfill the required lifetime imposed
by a higher-ranked trait bound
 --> /Users/tschottdorf/rust/i27114/main.rs:6:5
  |
6 |     foo::<&'b i32>();
  |     ^^^^^^^^^^^^^^
  |
  = note: type must outlive the static lifetime
note: which is implied by
 --> /Users/tschottdorf/rust/i27114/main.rs:3:23
  |
3 | fn foo<T>() where for<'a> T: 'a {}
  |                       ^^

error: aborting due to previous error
```

Fixes the simple case in #27114, though without attempting at all to handle
more complicated HRTBs (which is also discussed in said issue).

cc @eddyb