Tweak "value not found" error to show more context
Show enclosing item(s) where a name wasn't found. Show the enclosing item(s) for item that was found with the same name.

```
  --> $DIR/format-captured-non-values.rs:38:27
   |
LL | trait Report {
LL |     type Item;
   |          ---- an associated type by that name is available on `Self`
...
LL |         let _ = format!("{Item}");
   |                           ^^^^

error[E0425]: cannot find value `limit` in this scope
  --> $DIR/format-captured-non-values.rs:48:27
   |
LL | impl Report for () {
...
LL |     fn report(&self) {
LL |         // Label associated items instead of inserting `Self::` inside a capture.
LL |         let _ = format!("{limit}");
   |                           ^^^^^
   |
note: an associated function by that name is available on `Self`
  --> $DIR/format-captured-non-values.rs:36:5
   |
LL | trait Report {
LL |     type Item;
LL |     fn limit() -> usize { 3 }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
```

Use notes when pointing at items/fields of the same name that don't come from the current item.

```
error[E0425]: cannot find value `field` in this scope
  --> $DIR/field-and-method-in-self-not-available-in-assoc-fn.rs:12:15
   |
LL | impl Foo {
LL |     fn field(&self) -> u32 {
   |        ----- a method by that name is available on `Self` here
...
LL |     fn new() -> Foo {
LL |         field;
LL |         Foo { field }
   |               ^^^^^
   |
note: a field by that name exists in `Self`
  --> $DIR/field-and-method-in-self-not-available-in-assoc-fn.rs:2:5
   |
LL |     field: u32,
   |     ^^^^^
```