Don't run deploy script in integration tests
The deploy.sh was causing random integration tests to fail, possibly due to
multiple jobs trying to push to the same repo/branch at the same time?

The error message is:

    +git push git@github.com:rust-lang-nursery/rust-clippy.git gh-pages
    Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
    To github.com:rust-lang-nursery/rust-clippy.git
     ! [rejected]          gh-pages -> gh-pages (fetch first)
    error: failed to push some refs to 'git@github.com:rust-lang-nursery/rust-clippy.git'
    hint: Updates were rejected because the re

The travis log is always truncated in similar ways.

Some examples:

* https://travis-ci.org/rust-lang-nursery/rust-clippy/jobs/383325083#L1076-L1082
* https://travis-ci.org/rust-lang-nursery/rust-clippy/jobs/382711561#L2768-L2773