Improve live-drop precision
`State::join` uses a short-circuiting `||` when it should use `|`.

As a result:
- `self.borrow` sometimes is missing some bits it should have;
- which means `self.state.borrow.contains(local)` fails when it shouldn't;
- which means `!self.state.borrow.contains(local)` succeeds when it
  shouldn't;
- which means `self.state.qualif.remove(local);` runs when it shouldn't;

In practice, this means that some analysis information gets lost across
basic block boundaries, and the presence/absence of a simple branch or
function call or loop can change whether code is accepted or rejected.
Not good!

This bug has been present since this code was first added five years ago
in #90214.

This commit fixes that bug. But with the operator change alone we get
this compile error when building std:
```
error[E0493]: destructor of `MaybeDangling<P>` cannot be evaluated at compile-time
   --> library/core/src/mem/maybe_dangling.rs:102:29
    |
102 |     pub const fn into_inner(self) -> P
    |                             ^^^^ the destructor for this type cannot be evaluated in constant functions
...
111 |     }
    |     - value is dropped here
```

This is a case where a basic block boundary was preventing this code
from being rejected. We don't want to reject code that was previously
accepted due to a bug. Fortunately we can instead accept some code that
used to be rejected, by removing the qualif unconditionally in
`TransferFunction::visit_operand`. The existing behaviour is
conservative and the existing comment already says the check "might not
be strictly necessary" and was only present to match an older
implementation.

Removing the qualif unconditionally makes the vanilla const drop check
more precise, giving it some of the precision that the
`const_precise_live_drops` feature provides (just some whole move cases,
not the partial move cases), without requiring that feature's extra
machinery. This can be seen in the `issue-65394.rs` test, which now
compiles without needing the feature.