Silence errors in experssions caused by bare traits in paths
Address #51077 in editions>=2021 by treating `<Trait>` as a `<{type error}>` instead of `<dyn Trait>`, silencing subsequent errors. We new emit a single error ("missing `dyn`").

```
error[E0782]: trait objects must include the `dyn` keyword
 --> f800.rs:2:15
  |
2 | let x: u32 = <Default>::default();
  |               ^^^^^^^
  |
help: add `dyn` keyword before this trait
  |
2 | let x: u32 = <dyn Default>::default();
  |               +++
```

instead of 6

```
error[E0782]: trait objects must include the `dyn` keyword
 --> f800.rs:2:15
  |
2 | let x: u32 = <Default>::default();
  |               ^^^^^^^
  |
help: add `dyn` keyword before this trait
  |
2 | let x: u32 = <dyn Default>::default();
  |               +++

error[E0038]: the trait `Default` cannot be made into an object
 --> f800.rs:2:15
  |
2 | let x: u32 = <Default>::default();
  |               ^^^^^^^ `Default` cannot be made into an object
  |
  = note: the trait cannot be made into an object because it requires `Self: Sized`
  = note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>

error[E0277]: the size for values of type `dyn Default` cannot be known at compilation time
   --> f800.rs:2:15
    |
2   | let x: u32 = <Default>::default();
    |               ^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `dyn Default`
note: required by a bound in `default`
   --> /home/gh-estebank/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/default.rs:104:20
    |
104 | pub trait Default: Sized {
    |                    ^^^^^ required by this bound in `Default::default`
...
136 |     fn default() -> Self;
    |        ------- required by a bound in this associated function

error[E0308]: mismatched types
 --> f800.rs:2:14
  |
2 | let x: u32 = <Default>::default();
  |        ---   ^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `dyn Default`
  |        |
  |        expected due to this
  |
  = note:      expected type `u32`
          found trait object `dyn Default`
  = help: `u32` implements `Default` so you could change the expected type to `Box<dyn Default>`

error[E0038]: the trait `Default` cannot be made into an object
 --> f800.rs:2:14
  |
2 | let x: u32 = <Default>::default();
  |              ^^^^^^^^^^^^^^^^^^^^ `Default` cannot be made into an object
  |
  = note: the trait cannot be made into an object because it requires `Self: Sized`
  = note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>

error[E0277]: the size for values of type `dyn Default` cannot be known at compilation time
 --> f800.rs:2:14
  |
2 | let x: u32 = <Default>::default();
  |              ^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `dyn Default`
  = note: the return type of a function must have a statically known size
```