Test(lib/net): Fix `hostname_smoketest` for Win7
This test currently fails under both x86 and x86_64 Win7 on:

```
thread 'net::tests::hostname_smoketest' (2304) panicked at library/std/src/net/tests.rs:46:14:
called `Result::unwrap()` on an `Err` value: Error { kind: Unsupported, message: "operation not supported on this platform" }
```

This is simply because the feature was made to be effectively disabled
under these targets in PR 150905. The test is therefore fixed in order
to reflect that appropriately.

Signed-off-by: Paul Mabileau <paul.mabileau@harfanglab.fr>