core: io: clean `unused_variables` lint under `no_io_statics`
When building `core` with `--cfg no_io_statics`, the compiler warns:

    error: unused variable: `f`
     --> .../library/core/src/io/error/os_functions.rs:9:36
      |
    9 | pub(super) unsafe fn set_functions(f: &'static OsFunctions) {
      |                                    ^ help: if this is intentional, prefix it with an underscore: `_f`
      |
      = note: `-D unused-variables` implied by `-D warnings`
      = help: to override `-D warnings` add `#[allow(unused_variables)]`

Thus clean it up.

Signed-off-by: Miguel Ojeda <ojeda@kernel.org>