Use verbose suggestion for `mut binding` instead of `&mut binding`
```
error[E0308]: mismatched types
  --> $DIR/ref-pat-suggestions.rs:29:13
   |
LL |         let &mut _a = 0;
   |             ^^^^^^^   - this expression has type `{integer}`
   |             |
   |             expected integer, found `&mut _`
   |
   = note:           expected type `{integer}`
           found mutable reference `&mut _`
help: to declare a mutable variable use
   |
LL -         let &mut _a = 0;
LL +         let mut _a = 0;
   |
```