Improve live-drop precision
`State::join` uses a short-circuiting `||` when it should use `|`.

As a result:
- `self.borrow` sometimes is missing some bits it should have;
- which means `self.state.borrow.contains(local)` fails when it shouldn't;
- which means `!self.state.borrow.contains(local)` succeeds when it
  shouldn't;
- which means `self.state.qualif.remove(local);` runs when it shouldn't;

This bug has been present since this code was first added five years ago
in #90214.

This commit fixes that bug. But with that change alone we get this
compile error when building std:
```
error[E0493]: destructor of `MaybeDangling<P>` cannot be evaluated at compile-time
   --> library/core/src/mem/maybe_dangling.rs:102:29
    |
102 |     pub const fn into_inner(self) -> P
    |                             ^^^^ the destructor for this type cannot be evaluated in constant functions
...
111 |     }
    |     - value is dropped here
```

The fix for this is to remove the qualif unconditionally in
`TransferFunction::visit_operand`; indeed, the existing comment already
says the check "might not be strictly necessary".

This gives vanilla Rust some of the precision that the
`const_precise_live_drops` feature provides (just the whole move cases,
not the partial move cases), and would be a partial stabilization of the
feature. This can be seen in the `issue-65394.rs` test, which now
compiles without needing the feature.