On object safety errors, point at specific object unsafe trait in path
We use the new HIR node tracking for well-formedness obligations to
point at the specific trait object in a path/type (`dyn T` instead of a
whole `Box<dyn T>`, for example).

```
error[E0038]: the trait `MapLike` cannot be made into an object
  --> $DIR/file.rs:47:16
   |
LL |         as Box<dyn Trait>;
   |                ^^^^^^^^^ `Trait` cannot be made into an object
```

We also provide a structured suggestion for `<dyn Trait>::assoc`:

```
   = help: when writing `<dyn Trait>::function` you are requiring `Trait` be "object safe", which it isn't
help: you might have meant to access the associated function of a specific `impl` to avoid requiring "object safety" from `Trait`, either with some explicit type...
   |
LL |     </* Type */ as Trait>::function();
   |      ~~~~~~~~~~~~~
help: ...or rely on inference if the compiler has enough context to identify the desired type on its own...
   |
LL -     <dyn Trait>::function();
LL +     Trait::function();
   |
help: ...which is equivalent to
   |
LL |     <_ as Trait>::function();
   |      ~~~~
```