clippy: uibless new test output
In a couple of cases, adjust the test file, because otherwise the file
produces:

```
error: failed to apply suggestions for tests/ui/iter_overeager_cloned.rs with rustfix
cannot replace slice of data that was already replaced
Add //@no-rustfix to the test file to ignore rustfix suggestions
```