Make panic! error message GCC compatible
Reorders the output of thread error messages so that
the file:line location appears first on the line.

For example, this goes from

        thread 'test_fails' panicked at 'assertion failed: 0 == 1', src/main.rs:34

to

        src/main.rs:34: thread 'test_fails' panicked at 'assertion failed: 0 == 1'

Fixes: #25151