Use struct name as span instead of entire block
```
error[E0072]: recursive type `ListNode` has infinite size
  --> ../../../src/test/compile-fail/E0072.rs:11:8
   |
11 | struct ListNode { //~ ERROR E0072
   |        ^^^^^^^^ recursive type has infinite size
   |
   = help: insert indirection (e.g., a `Box`, `Rc`, or `&`) at some point to make `ListNode` representable
```