Fix documenting for non-x86 targets
These errors occur when cross compiling the LoongArch target on x86:

```
 Documenting std v0.0.0 (/home/hev/git/rust/rust/library/std)
error[E0412]: cannot find type `WSADATA` in this scope
   --> library/std/src/sys/windows/c/windows_sys.rs:715:63
    |
715 |     pub fn WSAStartup(wversionrequested: u16, lpwsadata: *mut WSADATA) -> i32;
    |                                                               ^^^^^^^ not found in this scope

error[E0412]: cannot find type `CONTEXT` in this scope
    --> library/std/src/sys/windows/c/windows_sys.rs:3034:29
     |
3034 |     pub ContextRecord: *mut CONTEXT,
     |                             ^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0412`.
error: could not document `std`
```

Fixes: e92ee0355 ("Generate windows-sys bindings")