fix: no lint unsized adt self_ty missing bounded assoc
Example
---
```rust
trait Trait {
    fn item() where Self: Sized;
}
impl Trait for Adt {}
struct Adt([i32]);
```

**Before this PR**

```
error: not all trait items implemented, missing: `fn item`
```

**After this PR**

no lint