Introduce `default_could_be_derived` lint
New lint that detects when an enum with no type paremeters has a manual `Default` impl that uses a single unit variant and suggests deriving instead.

```
error: `impl Default` that could be derived
  --> $DIR/manual-default-impl-could-be-derived.rs:58:1
   |
LL | / impl Default for F {
LL | |     fn default() -> Self {
LL | |         F::Unit
LL | |     }
LL | | }
   | |_^
   |
note: the lint level is defined here
  --> $DIR/manual-default-impl-could-be-derived.rs:4:9
   |
LL | #![deny(default_could_be_derived)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^
help: you don't need to manually `impl Default`, you can derive it
   |
LL ~ #[derive(Default)] enum F {
LL ~     #[default] Unit,
   |
```

The rendering of the suggestion doesn't include the deletion, but it is there and gets machine applied.