Tweak output for note pointing at root cause of const error
```
error[E0080]: evaluation of constant value failed
  --> $DIR/issue-81899.rs:4:24
   |
LL | const _CONST: &[u8] = &f(&[], |_| {});
   |                        ^^^^^^^^^^^^^^ panic: explicit panic
   |
note: the evaluated program failed inside `f::<{closure@$DIR/issue-81899.rs:4:31: 4:34}>`
  --> $DIR/issue-81899.rs:11:5
   |
LL |     panic!()
   |     ^^^^^^^^ the evaluated program failed here
   = note: this error originates in the macro `$crate::panic::panic_2015` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)
```