Update rustc_codegen_cranelift's dependencies
The build of rustc_codegen_cranelift is currently broken
because of a build issue with its dependency libc:

  Compiling libc v0.2.148
  error: invalid `--check-cfg` argument: `values(emscripten_new_stat_abi)`
    (expected `cfg(name, values("value1", "value2", ... "valueN"))`)
  [RUSTC-TIMING] libc test:false 0.332
  error: could not compile `libc` (lib) due to 1 previous error

Let's update Cargo.lock to resolve this issue.

Signed-off-by: Christoph Müllner <christoph.muellner@vrull.eu>