Provide context of enclosing item on `self` that takes ownership
```
error[E0507]: cannot move out of `*foo` which is behind a shared reference
  --> $DIR/clone-span-on-try-operator.rs:10:5
   |
LL |     (*foo).foo();
   |     ^^^^^^ ----- `*foo` moved due to this method call
   |     |
   |     move occurs because `*foo` has type `Foo`, which does not implement the `Copy` trait
   |
note: `Foo::foo` takes ownership of the receiver `self`, which moves `*foo`
  --> $DIR/clone-span-on-try-operator.rs:6:12
   |
LL | impl Foo {
LL |     fn foo(self) {}
   |            ^^^^
help: consider cloning the value if the performance cost is acceptable
   |
LL -     (*foo).foo();
LL +     foo.clone().foo();
   |
```