core: add core::pattern::Predicate wrapper type
To work around orphan rules, introduce a wrapper type for predicate
functions to be used as pattern.  Specefically, if we want to add
predicat pattern implementation for OsStr type, doing it with a naked
`FnMut` results in compile-time errors:

    error[E0210]: type parameter `F` must be covered by another type when it
                  appears before the first local type (`OsStr`)
    impl<'hs, F: FnMut(char) -> bool> core::pattern::Pattern<&'hs OsStr> for F {
              ^ type parameter `F` must be covered by another type
                when it appears before the first local type (`OsStr`)