Detect missing `;` on methods with return type `()`
On a given file `foo.rs`:

```rust
fn foo() {
    return 1;
}

fn main() {
    3
}
```

Provide the following output:

```bash
error[E0308]: mismatched types
 --> foo.rs:2:12
  |
1 | fn foo() {
  |          ^ possibly return type `{integer}` missing in this fn?
2 |     return 1;
  |            ^ expected (), found integral variable
  |
  = note: expected type `()`
  = note:    found type `{integer}`

error[E0308]: mismatched types
 --> foo.rs:6:5
  |
6 |     3
  |     ^
  |     |
  |     possibly `;` missing here?
  |     expected (), found integral variable
  |
  = note: expected type `()`
  = note:    found type `{integer}`

error: aborting due to 2 previous errors
```