Update `vec!` to have the same coercion behavior as arrays
Before this commit, `vec![a, b, c]` had different coercion behavior than the
array `[a, b, c]`. Example:

    fn foo() {}
    fn bar() {}

    let arr = [foo, bar];    // works, fn items coerced to fn pointer
    let v = vec![foo, bar];  // doesn't work

Last line results in:

    error[E0308]: mismatched types
     --> src/main.rs:6:13
      |
    6 |     let v = vec![foo, bar];  // doesn't work
      |             ^^^^^^^^^^^^^^ expected slice, found array of 2 elements
      |
      = note: expected type `std::boxed::Box<[fn() {main::foo}]>`
                 found type `std::boxed::Box<[fn(); 2]>`

This is due to `box [a, b, c]` behaving a bit strangely. A very related
question on StackOverflow: https://stackoverflow.com/q/54632524/2408867

By introducing this temporary let binding, we can fix the coercion
behavior. I'm pretty sure this is not a breaking change as it only
allows more cases to compile.