update some compile-fail tests
Some errors, about trait objects not implementing their own trait when
they aren’t object-safe, aren’t being reported. Here is the error
missing from compile-fail/trait-test-2.rs:

```
error[E0277]: the trait bound `dyn bar: bar` is not satisfied
  --> src/test/compile-fail/trait-test-2.rs:20:26
   |
20 |     (box 10 as Box<bar>).dup();
   |                          ^^^ the trait `bar` is not implemented
for `dyn bar`
```

My best guess is it has to do with how object-safety checks now include
trait-solving. It doesn’t look like a very useful error, so I’m not too
worried.