Detect missing `;` on methods with return type `()`
On a given file `foo.rs`:

```rust
fn foo() {
    return 1;
}

fn bar() {
    3
}

fn main() {
    3
}
```

Provide the following output:

```bash
error[E0308]: mismatched types
 --> foo.rs:2:12
  |
2 |     return 1;
  |            ^ expected (), found integral variable
  |
  = note: expected type `()`
  = note:    found type `{integer}`

error[E0308]: mismatched types
 --> foo.rs:6:5
  |
5 | fn bar() {
  |          - possibly return type `{integer}` missing here
6 |     3
  |     ^- consider adding a semicolon here
  |     |
  |     expected (), found integral variable
  |
  = note: expected type `()`
  = note:    found type `{integer}`

error[E0308]: mismatched types
  --> foo.rs:10:5
   |
10 |     3
   |     ^- consider adding a semicolon here
   |     |
   |     expected (), found integral variable
   |
   = note: expected type `()`
   = note:    found type `{integer}`

error: aborting due to 3 previous errors
```