Introduce `llvm-enable-rtti` option
This option is controls when LLVM build adds `-fno-rtti`. Some details
available here: https://www.llvm.org/docs/HowToSetUpLLVMStyleRTTI.html

When this option is enabled, llvm build produces a bit more symbols:
````
rust % nm build/x86_64-apple-darwin/llvm/lib/libLLVMCore.a | grep llvm10CallbackVHE
0000000000007120 S __ZTIN4llvm10CallbackVHE
0000000000007240 S __ZTSN4llvm10CallbackVHE
00000000000070e8 S __ZTVN4llvm10CallbackVHE
````
and just to compare the same build without this option (current behaviour):
```
rust % nm build/x86_64-apple-darwin/llvm/lib/libLLVMCore.a | grep llvm10CallbackVHE
00000000000070b8 S __ZTVN4llvm10CallbackVHE
```

An attempt to bootstrap `rust` with `clang` which was built with enabled
RTTI may fail with linking error like:
```
 = note: dyld: Symbol not found: __ZTIN4llvm10CallbackVHE
            Referenced from: /opt/local/libexec/llvm-9.0/bin/../lib/libclang-cpp.dylib
            Expected in: .../build/x86_64-apple-darwin/stage2/lib/libLLVM.dylib
           in /opt/local/libexec/llvm-9.0/bin/../lib/libclang-cpp.dylib
```