attempt to register the helper macro so that it allows unstable things internally.
Unfortunately, i am having issues getting this to actually work.

I repeatedly see:

```
failures:
    [run-fail] run-fail/explicit-panic-msg.rs
```

Namely:

```
failures:

---- [run-fail] run-fail/explicit-panic-msg.rs stdout ----

error: compilation failed!
status: exit code: 101
command: x86_64-apple-darwin/stage2/bin/rustc /Users/fklock/Dev/Mozilla/rust-panic/src/test/run-fail/explicit-panic-msg.rs -L x86_64-apple-darwin/test/run-fail/ --target=x86_64-apple-darwin -L x86_64-apple-darwin/test/run-fail/explicit-panic-msg.stage2-x86_64-apple-darwinlibaux -C prefer-dynamic -o x86_64-apple-darwin/test/run-fail/explicit-panic-msg.stage2-x86_64-apple-darwin --cfg rtopt --cfg debug -L x86_64-apple-darwin/rt
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
<std macros>:2:26: 2:57 error: use of unstable library feature 'core': internal to format_args!
<std macros>:2 $ crate:: fmt:: format ( format_args ! ( $ ( $ arg ) * ) ) )
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: in expansion of __unstable_rustc_ensure_not_fmt_string_literal!
<std macros>:4:1: 4:78 note: expansion site
<std macros>:1:1: 12:23 note: in expansion of panic!
/Users/fklock/Dev/Mozilla/rust-panic/src/test/run-fail/explicit-panic-msg.rs:18:5: 18:37 note: expansion site
<std macros>:2:26: 2:57 help: add #![feature(core)] to the crate attributes to enable
<std macros>:2:26: 2:57 error: use of unstable library feature 'core': internal to format_args!
<std macros>:2 $ crate:: fmt:: format ( format_args ! ( $ ( $ arg ) * ) ) )
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: in expansion of __unstable_rustc_ensure_not_fmt_string_literal!
<std macros>:4:1: 4:78 note: expansion site
<std macros>:1:1: 12:23 note: in expansion of panic!
/Users/fklock/Dev/Mozilla/rust-panic/src/test/run-fail/explicit-panic-msg.rs:18:5: 18:37 note: expansion site
<std macros>:2:26: 2:57 help: add #![feature(core)] to the crate attributes to enable
error: aborting due to 2 previous errors

------------------------------------------
```

and I have not yet figured out why this happens even now, nor
how to resolve it.