proc_macro::Span::at_start and at_end
Before this addition, every delimited group like (...) [...] {...} has
only a single Span that covers the full source location from opening
delimiter to closing delimiter. This makes it impossible for a
procedural macro to trigger an error pointing to just the opening or
closing delimiter. The Rust compiler does not seem to have the same
limitation:

    mod m {
        type T =
    }

    error: expected type, found `}`
     --> src/main.rs:3:1
      |
    3 | }
      | ^

On that same input, a procedural macro would be forced to trigger the
error on the last token inside the block, on the entire block, or on the
next token after the block, none of which is really what you want for an
error like above.

This commit adds span.at_start() and span.at_end() which access the Span
associated with just the first byte (opening delimiter) and just the
last byte (closing delimiter) of the group. Relevant to Syn as we
implement real error messages for when parsing fails in a procedural
macro.