Fix argument order in printed output on panic
Before this commit, the output printed when panicking was:

> Thread 'name' panicked at 'msg', location

when it should have been:

> Thread 'name' panicked at location, 'msg'

This bug was originally introduced in 576f59a. The message was changed
to something which implies the location comes before the message,
without changing the order of the arguments. A similar change was made
in f8a4d09, with the only reason given being consistency between the
Rust runtime and C++ runtime. We could also go back towards something
closer to that message ("Thread 'name' panicked: 'msg' at location"), I
don't really have any preference.